video:
  source: video.mp4  # Traffic intersection video
  display_preview: true
  target_fps: 15
model:
  weights: yolo11x.pt  # YOLO11x (most accurate available)
  confidence: 0.1
  device: cuda
  classes_to_detect:
  - 2
  - 3
  - 5
redis:
  host: localhost
  port: 6379
  db: 0
traffic:
  streets:
    street_1:
      roi:
      - - 812
        - 15
      - - 1541
        - 14
      - - 1818
        - 206
      - - 1908
        - 244
      - - 2007
        - 274
      - - 2150
        - 254
      - - 2295
        - 159
      - - 2394
        - 43
      - - 2435
        - 12
      - - 2581
        - 2
      - - 2468
        - 120
      - - 2328
        - 275
      - - 2189
        - 357
      - - 2059
        - 393
      - - 1971
        - 391
      - - 1862
        - 365
      - - 1771
        - 322
      - - 2025
        - 530
      - - 2328
        - 787
      - - 2692
        - 1064
      - - 2709
        - 1063
      - - 2806
        - 956
      - - 2833
        - 971
      - - 2816
        - 1067
      - - 2815
        - 1116
      - - 2929
        - 1112
      - - 2936
        - 1171
      - - 2991
        - 1324
      - - 3064
        - 1401
      - - 3194
        - 1509
      - - 3824
        - 2062
      - - 3834
        - 2129
      - - 3833
        - 2148
      - - 3368
        - 2149
      - - 3309
        - 2148
      - - 2539
        - 1505
      - - 1640
        - 731
      - - 810
        - 15
      max_vehicles: 90
      redis_key: urbanflow:traffic:street_1
    street_2:
      roi:
      - - 3299
        - 2151
      - - 2575
        - 2153
      - - 2259
        - 1911
      - - 1477
        - 1257
      - - 1234
        - 919
      - - 1196
        - 942
      - - 1248
        - 1130
      - - 1249
        - 1276
      - - 1149
        - 1267
      - - 1152
        - 1190
      - - 1142
        - 1111
      - - 1117
        - 1012
      - - 1080
        - 937
      - - 1019
        - 848
      - - 761
        - 640
      - - 343
        - 276
      - - 441
        - 114
      - - 630
        - 3
      - - 954
        - 283
      - - 1545
        - 801
      - - 1633
        - 783
      - - 2076
        - 533
      - - 2315
        - 286
      - - 2586
        - 5
      - - 2967
        - 1
      - - 2390
        - 625
      - - 2202
        - 759
      - - 2137
        - 934
      - - 2127
        - 1133
      - - 2169
        - 1323
      - - 2331
        - 1562
      - - 2507
        - 1594
      - - 2793
        - 1819
      - - 2895
        - 1898
      - - 2974
        - 1965
      - - 3066
        - 2050
      - - 3152
        - 2108
      - - 3202
        - 2143
      - - 3294
        - 2146
      max_vehicles: 20
      redis_key: urbanflow:traffic:street_2
    street_3:
      roi:
      - - 3170
        - 3
      - - 3811
        - 13
      - - 2981
        - 898
      - - 2670
        - 1101
      - - 1506
        - 2151
      - - 1003
        - 2148
      - - 1615
        - 1594
      - - 2432
        - 789
      - - 2900
        - 273
      - - 3170
        - 1
      max_vehicles: 20
      redis_key: urbanflow:traffic:street_3
    street_4:
      roi:
      - - 775
        - 2154
      - - 904
        - 2153
      - - 1576
        - 1569
      - - 2489
        - 545
      - - 2981
        - 1
      - - 2591
        - 1
      - - 2093
        - 526
      - - 1434
        - 1294
      - - 1201
        - 1505
      - - 793
        - 1836
      - - 399
        - 2153
      - - 771
        - 2143
      - - 775
        - 2149
      max_vehicles: 20
      redis_key: urbanflow:traffic:street_4
parking:
  spots: {}  # No parking spots defined for traffic video yet
emergency:
  vehicle_class: 7
  track_all: true
  redis_key_prefix: urbanflow:emergency:truck_

speed_detection:
  pixels_per_meter: 31.3  # Calibrated: 140.86 pixels = 4.5m car
  speed_limit_kmh: 50
  calibration_distance_m: 4.5
  calibration_distance_px: 140.86

